### ISSUE TITLE
Send for links not in h-entry

### ISSUE THREAD

**Issue by singpolyma** [indieweb/mention-client-ruby#10]
Why require all links to be notified go in an h-entry body?

**Comment by aaronpk** [comment]
The majority of the use of this gem is for sending webmentions from sites that use `h-entry`, since it's expected that the receiver will go parse the page and find the `h-entry` on the sending site. Without the filter of only finding links inside the `h-entry`, this gem would end up sending a bunch of webmentions to pages such as links in navigation or the site footer, which is usually not the desired result.

**Comment by singpolyma** [comment]
I'm also using h-entry (well, hentry) -- I guess pinging nav links could be a lot more work if there are many of them? Or is there a fear that the nav link targets actually support webmention? I guess for nex/prev links, hmmm. Ok
